# Generated by Django 5.0.1 on 2024-02-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_products_delete_prosucts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='data_of_creating',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='products',
            name='date_last_change',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
