# Generated by Django 5.0.1 on 2024-02-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_products_data_of_creating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='data_of_creating',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='date_last_change',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='products',
            name='price_for_unit',
            field=models.IntegerField(verbose_name='Цена за единицу товара'),
        ),
    ]
