# Generated by Django 5.0.1 on 2024-02-16 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_data_of_creating_products_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.categories'),
        ),
    ]
