# Generated by Django 5.0.1 on 2024-03-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_contacts_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=110, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='номер телефона'),
        ),
    ]
