# Generated by Django 5.0.1 on 2024-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_contacts_name_alter_contacts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='products',
            name='views_counter',
            field=models.IntegerField(default=0, verbose_name='кол-во просмотров'),
        ),
    ]
