# Generated by Django 5.0.1 on 2024-03-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_products_is_published_products_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=60, verbose_name='Версия продукта')),
                ('version_num', models.CharField(default='1.0.0', max_length=150, verbose_name='Номер версии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Версия активна')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия продукта',
                'verbose_name_plural': 'Версии продукта',
                'ordering': ('version_num',),
            },
        ),
    ]
