# Generated by Django 5.0.1 on 2024-03-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_versionproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionproduct',
            name='last_update',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата применения последней версии'),
        ),
    ]
